
//not ideal but better than fetching the country name outside of the app.
Map codeToCountry = {
  "AED": "United Arab Emirates",
  "AFN": "Afghanistan",
  "ALL": "Albania",
  "AMD": "Armenia",
  "ANG": "Netherlands Antilles",
  "AOA": "Angola",
  "ARS": "Argentina",
  "AUD": "Australia",
  "AWG": "Aruba",
  "AZN": "Azerbaijan",
  "BAM": "Bosnia and Herzegovina",
  "BBD": "Barbados",
  "BDT": "Bangladesh",
  "BGN": "Bulgaria",
  "BHD": "Bahrain",
  "BIF": "Burundi",
  "BMD": "Bermuda",
  "BND": "Brunei",
  "BOB": "Bolivia",
  "BOV": "Bolivia",
  "BRL": "Brazil",
  "BSD": "Bahamas",
  "BTN": "Bhutan",
  "BWP": "Botswana",
  "BYR": "Belarus",
  "BZD": "Belize",
  "CAD": "Canada",
  "CDF": "Democratic Republic of Congo",
  "CHE": "Switzerland",
  "CHF": "Switzerland",
  "CHW": "Switzerland",
  "CLF": "Chile",
  "CLP": "Chile",
  "CNY": "Mainland China",
  "COP": "Colombia",
  "COU": "Colombia",
  "CRC": "Costa Rica",
  "CUP": "Cuba",
  "CVE": "Cape Verde",
  "CYP": "Cyprus",
  "CZK": "Czech Republic",
  "DJF": "Djibouti",
  "DKK": "Denmark",
  "DOP": "Dominican Republic",
  "DZD": "Algeria",
  "EEK": "Estonia",
  "EGP": "Egypt",
  "ERN": "Eritrea",
  "ETB": "Ethiopia",
  "EUR": "European Union",
  "FJD": "Fiji",
  "FKP": "Falkland Islands",
  "GBP": "United Kingdom",
  "GEL": "Georgia",
  "GHS": "Ghana",
  "GIP": "Gibraltar",
  "GMD": "Gambia",
  "GNF": "Guinea",
  "GTQ": "Guatemala",
  "GYD": "Guyana",
  "HKD": "Hong Kong",
  "HNL": "Honduras",
  "HRK": "Croatia",
  "HTG": "Haiti",
  "HUF": "Hungary",
  "IDR": "Indonesia",
  "ILS": "Israel",
  "INR": "Bhutan, India",
  "IQD": "Iraq",
  "IRR": "Iran",
  "ISK": "Iceland",
  "JMD": "Jamaica",
  "JOD": "Jordan",
  "JPY": "Japan",
  "KES": "Kenya",
  "KGS": "Kyrgyzstan",
  "KHR": "Cambodia",
  "KMF": "Comoros",
  "KPW": "North Korea",
  "KRW": "South Korea",
  "KWD": "Kuwait",
  "KYD": "Cayman Islands",
  "KZT": "Kazakhstan",
  "LAK": "Laos",
  "LBP": "Lebanon",
  "LKR": "Sri Lanka",
  "LRD": "Liberia",
  "LSL": "Lesotho",
  "LTL": "Lithuania",
  "LVL": "Latvia",
  "LYD": "Libya",
  "MAD": "Morocco",
  "MDL": "Moldova",
  "MGA": "Madagascar",
  "MKD": "Former Yugoslav Republic of Macedonia",
  "MMK": "Myanmar",
  "MNT": "Mongolia",
  "MOP": "Macau Special Administrative Region",
  "MRO": "Mauritania",
  "MTL": "Malta",
  "MUR": "Mauritius",
  "MVR": "Maldives",
  "MWK": "Malawi",
  "MXN": "Mexico",
  "MXV": "Mexico",
  "MYR": "Malaysia",
  "MZN": "Mozambique",
  "NAD": "Namibia",
  "NGN": "Nigeria",
  "NIO": "Nicaragua",
  "NOK": "Norway",
  "NPR": "Nepal",
  "NZD": "New Zealand",
  "OMR": "Oman",
  "PAB": "Panama",
  "PEN": "Peru",
  "PGK": "Papua New Guinea",
  "PHP": "Philippines",
  "PKR": "Pakistan",
  "PLN": "Poland",
  "PYG": "Paraguay",
  "QAR": "Qatar",
  "RON": "Romania",
  "RSD": "Serbia",
  "RUB": "Russia",
  "RWF": "Rwanda",
  "SAR": "Saudi Arabia",
  "SBD": "Solomon Islands",
  "SCR": "Seychelles",
  "SDG": "Sudan",
  "SEK": "Sweden",
  "SGD": "Singapore",
  "SHP": "Saint Helena",
  "SKK": "Slovakia",
  "SLL": "Sierra Leone",
  "SOS": "Somalia",
  "SRD": "Suriname",
  "STD": "São Tomé and Príncipe",
  "SYP": "Syria",
  "SZL": "Swaziland",
  "THB": "Thailand",
  "TJS": "Tajikistan",
  "TMM": "Turkmenistan",
  "TND": "Tunisia",
  "TOP": "Tonga",
  "TRY": "Turkey",
  "TTD": "Trinidad and Tobago",
  "TWD": "Taiwan (ROC)",
  "TZS": "Tanzania",
  "UAH": "Ukraine",
  "UGX": "Uganda",
  "USD": "United States",
  "USN": "United States",
  "USS": "United States",
  "UYU": "Uruguay",
  "UZS": "Uzbekistan",
  "VEB": "Venezuela",
  "VND": "Vietnam",
  "VUV": "Vanuatu",
  "WST": "Samoa",
  "XAF": "Cameroon",
  "YER": "Yemen",
  "ZAR": "South Africa",
  "ZMK": "Zambia",
  "ZWD": "Zimbabwe"
};
